// design-sync bundle entry: the UI kit surface synced to claude.ai/design.
// Mirrored by types/index.d.ts (generated by gen-types.mjs) — keep both lists in sync.

// Must stay the FIRST import: claims react-native-web's style element under an
// id that doesn't shadow preview mount roots (see the shim for why).
import "./shims/rnw-stylesheet-id";

// Initializes i18next with the app's real translations so components calling
// t() (BackButton) render copy, not raw keys. The app inits at lng "de" and
// switches asynchronously; previews force "en" up front so the first paint is
// already the final language and screenshots can't race the switch.
import i18n from "../lib/i18n/i18n";

i18n.changeLanguage("en");
export { BackButton } from "../lib/components/ui/BackButton";
export { Badge } from "../lib/components/ui/Badge";
export { BottomSheet } from "../lib/components/ui/BottomSheet";
export { Button } from "../lib/components/ui/Button";
export { ChipGroup } from "../lib/components/ui/ChipGroup";
export { Combobox } from "../lib/components/ui/Combobox";
export { DataTable } from "../lib/components/ui/DataTable";
export { DialogProvider, useDialog } from "../lib/components/ui/Dialog";
export { DirectionPicker } from "../lib/components/ui/DirectionPicker";
export { EmptyState } from "../lib/components/ui/EmptyState";
export { FormField } from "../lib/components/ui/FormField";
export { InfoButton } from "../lib/components/ui/InfoButton";
export { Markdown } from "../lib/components/ui/Markdown";
export { PieChart } from "../lib/components/ui/PieChart";
export { ResizableTextInput } from "../lib/components/ui/ResizableTextInput";
export { SearchInput } from "../lib/components/ui/SearchInput";
export { SelectPicker } from "../lib/components/ui/SelectPicker";
export { ThemeProvider, useTheme } from "../lib/bootstrap/ThemeProvider";
// Layout primitives the components compose with. Re-exported (react-native →
// react-native-web via tsconfig.sync.json) because an RN component library is
// unusable without them: any app built from this kit needs View/Text/StyleSheet
// to lay the components out. Excluded from component cards via componentSrcMap.
export {
  ActivityIndicator,
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
export { dark, oled, light, highContrast, palettes, colors } from "../lib/theme/colors";
export { space, inset } from "../lib/theme/spacing";
export { fonts, type } from "../lib/theme/typography";
export { ui } from "../lib/theme/ui";
